### ISSUE TITLE
Enhancement of Readme.MD

### ISSUE THREAD

**Issue by kanishkaa24** [geekymeeky/JS-games#57]
- This is a documentation enhancement issue.
- Comment your ideas with relevant references to improve the appearance of the markdown file (eg. Add images, gifs, status, details)
- Issue will be assigned on the basis of your idea and FCFS basis.
- Kindly fill the below template while suggesting the improvement.

### Template

 **Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snehaM2210** [comment]
Can you assign this issue to me..I would love to work on it @kanishkaa24 .
I would like to include a brief introduction part in the readme about the project and will include the tech stacks needed for it, how it can be useful and what is the importance of this project.
I would also include svg, img(of few games during playing) or emojis to make the readme more attractive !
While submitting the PR I will surely upload the screenshot so that it will be easier for you to review and merge.
Kindly assign me.
